name: Entry Dispatcher

on:
  pull_request:
    branches:
      - main
    paths:
      - 'Java/IMS.BavaServices/**'
      - 'Java/IMS.JavaServices/**'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          echo "BAVA_CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep 'Java/IMS.BavaServices/' | wc -l)" >> $GITHUB_ENV
          echo "JAVA_CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep 'Java/IMS.JavaServices/' | wc -l)" >> $GITHUB_ENV

      - name: Echo paths changed
        run: |
          echo "BAVA Services changed: $BAVA_CHANGED"
          echo "JAVA Services changed: $JAVA_CHANGED"

      - name: Trigger IMS BAVA Service WF
        if: ${{ env.BAVA_CHANGED }} != '0'
        uses: actions/github-script@v3
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ims-bava-svcs.yml',
              ref: 'refs/heads/main'
            })
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger IMS JAVA Service WF
        if: ${{ env.JAVA_CHANGED }} != '0'
        uses: actions/github-script@v3
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ims-java-svcs.yml',
              ref: 'refs/heads/main'
            })
          github-token: ${{ secrets.GITHUB_TOKEN }}
