name: Entry Dispatcher

on:
  pull_request:
    branches:
      - main
    paths:
      - 'Java/IMS.BavaServices/**'
      - 'Java/IMS.JavaServices/**'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get list of changed files
        id: get_changed_files
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pull_number = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            const listFilesOptions = github.rest.pulls.listFiles.endpoint.merge({
              owner,
              repo,
              pull_number
            });
            
            const listFilesResponse = await github.paginate(listFilesOptions);
            const changedFiles = listFilesResponse.map(file => file.filename);
            
            core.setOutput('changed_files', changedFiles.join(','));

      - name: Echo changed files
        run: echo "Changed files: ${{ steps.get_changed_files.outputs.changed_files }}"

      - name: Trigger IMS BAVA Service WF
        if: contains(steps.get_changed_files.outputs.changed_files, 'Java/IMS.BavaServices/')
        uses: actions/github-script@v3
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ims-bava-svcs.yml',
              ref: context.ref
            })
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger IMS JAVA Service WF
        if: contains(steps.get_changed_files.outputs.changed_files, 'Java/IMS.JavaServices/')
        uses: actions/github-script@v3
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ims-java-svcs.yml',
              ref: context.ref
            })
          github-token: ${{ secrets.GITHUB_TOKEN }}
