name: Entry Dispatcher

on:
  pull_request:
    branches:
      - main
    paths:
      - 'Java/IMS.BavaServices/**'
      - 'Java/IMS.JavaServices/**'

jobs:
  blockprdispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Echo changed files
        run: echo "Changed files:" ${{ toJson(github.event.pull_request.files.*.filename) }}


      - name: Trigger IMS BAVA Service WF
        if: contains(toJSON(github.event.pull_request.files.*.filename), 'Java/IMS.BavaServices/')
        uses: actions/github-script@v3
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ims-bava-svcs.yml',
              ref: context.ref
            })
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger IMS JAVA Service WF
        if: contains(toJSON(github.event.pull_request.files.*.filename), 'Java/IMS.JavaServices/')
        uses: actions/github-script@v3
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ims-java-svcs.yml',
              ref: context.ref
            })
          github-token: ${{ secrets.GITHUB_TOKEN }}
