name: IMS Bava Build Test

on:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and Test
        run: echo "Running Job System build and tests"
