name: Entry Single Dispatcher

on:
  pull_request:
    branches:
      - main
    paths:
      - 'Java/IMS.BavaServices/**'
      - 'Java/IMS.JavaServices/**'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get list of changed files
        id: files
        run: |
          changes=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          bavaChanged=false
          javaChanged=false
          for file in $changes; do
            if [[ $file == 'Java/IMS.BavaServices/'* ]]; then
              bavaChanged=true
            elif [[ $file == 'Java/IMS.JavaServices/'* ]]; then
              javaChanged=true
            fi
          done
          echo "::set-output name=bavaChanged::$bavaChanged"
          echo "::set-output name=javaChanged::$javaChanged"

      - name: Output file checks
        run: |
          echo "BAVA Services changed: ${{ steps.files.outputs.bavaChanged }}"
          echo "JAVA Services changed: ${{ steps.files.outputs.javaChanged }}"

      - name: Trigger IMS BAVA Service WF
        if: steps.files.outputs.bavaChanged == 'true'
        run: echo "Trigger IMS BAVA Service Workflow"
        # Add your commands to trigger the BAVA Service workflow here

      - name: Trigger IMS JAVA Service WF
        if: steps.files.outputs.javaChanged == 'true'
        run: echo "Trigger IMS JAVA Service Workflow"
        # Add your commands hre to trigger the JAVA Service workflow here
